# Generated by Django 2.2.5 on 2019-09-26 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CraigslistApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
