# Generated by Django 2.2.5 on 2019-09-30 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CraigslistApp', '0002_auto_20190926_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='searchField',
            new_name='search',
        ),
    ]
